baseURL = "https://suubro.github.io/Seqoli/"
publishDir = "../docs/"
languageCode = "en"
title = "Seqoli"
theme = "html"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Features"
url     = "features"
weight  = 2
[[menu.main]]
name    = "User Guide"
url     = "userguide"
weight  = 3
[[menu.main]]
name    = "Download"
url     = "https://gumroad.com/l/seqoli"
weight  = 4
[[menu.main]]
name    = "GitHub"
url     = "https://github.com/SuuBro/Seqoli"
weight  = 5

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "SuuBro"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
headerImg = "images/logo_black.png"
heading = "Seqoli"
description = "An open-source project for ROLI Blocks"
btn     = true
btnText = "Download Now"
btnURL  = "https://gumroad.com/l/seqoli"

# flip text
#[[params.banner.flipText]]
#title   = "Open Source"
[[params.banner.flipText]]
title   = "Tactile MIDI Sequencer"
#[[params.banner.flipText]]
#title   = "Expandable"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT SEQOLI"
content = "Seqoli is a 'DAW-less' midi sequencer interface designed to run on one or more ROLI Lightpad BLOCKS. Drawing inspiration from Monome grid, Seqoli is great for creating polyrhythms on the fly or sequencing an entire track. Snap together multiple Lightpad BLOCKS to extend your sequencer length and/or track count."
image   = "images/Example.png"

# Call to Action
[params.cta]
enable  = true
title   = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
